### ISSUE TITLE
Cluster Support

### ISSUE THREAD

**Issue by jmacd3** [statsite/statsite#12]
I have a federated graphite cluster that uses consistent hashing setup as follows:

![Graphite Cluster](http://img.ksl.com/ksllocal/73752.jpg)

My statsite instances flush every 10 seconds. 

I want to be able to load-balance requests to any node in the cluster. The problem is that samples of any given metric will most likely be sent to more than one statsite instance within the 10 second flush interval. When the statsite instances flush there will be a race condition that will cause colliding metrics to overwrite one another. I toyed with the idea of using aggregators to address this issue. Aggregators would work fine for counts and kv as because I could sum the counts and average the kv metrics. Dealing with the timing stats however is not so straight forward. I would have write my own weighted average method. Additionally, I would have to mess with the consistent hashing mechanism to make sure that all the stats derived from a specific timing metric arrive at the same aggregator. Even with all this in place I am still not sure what to do with the standard deviations and percentile stats. I would probably just have to throw them away. This is obviously not a clean or ideal solution. 

Alternatively, I decided it would be much better to do consistent hashing before statsite aggregates the metrics. This way I don't have to worry about merging aggregated results from multiple statsite instances. This could be handled on the client side but I really want to address this issue on the server side. 

My plan is to extend your statsite to handle the consistent hashing and relaying of metrics to the appropriate statsite instance.

I would add a couple parameters to the config to enable relaying and to specify the other statsite destinations.

Whenever a metric is recieved before processing it, I would hash on the metric name and then if necessary forward it to another statsite instance. If the stat does not need to be forwarded it would be processed as normal.

Do you accept pull request?

Also, have you ever run into a similar situation or can you think of any pitfalls to this approach?

**Comment by hit9** [comment]
@armon 

```
client_A -> statsite_A
client_B -> statsite_B
...
```
Each client send streams to their own statsite, that solves the issue.

Or to make a proxy like twemproxy (via consistent hashing), one metric is always sent to some statsite.

**Comment by armon** [comment]
I think the statsite-proxy project by @jmacd3 was like twemproxy but for statsite. There is now another project too https://github.com/uber/statsrelay for the same purpose
