### ISSUE TITLE
Migrate to statsite 'organisation'?

### ISSUE THREAD

**Issue by johnkeates** [statsite/statsite#217]
It seems the author simply doesn't have the time to keep track of all the issues and PR's (which makes sense, it's a lot of work+time), so maybe it's a good idea to have some sort of group or organisation with more people that can accept PR's?

**Comment by filippog** [comment]
Agreed, I think it'd make sense if more contributors could merge PRs and avoid maintaining long-lived forks

**Comment by johnkeates** [comment]
I hope @armon has a few minutes to spare to say something about this. If he is too busy (which does happen, work gets in the way quite often for me as well), we could always just decide to set up an "official" fork.

**Comment by theatrus** [comment]
Happy to help with the project if it branches out into an org, and possibly work on moving our long-running fork into the main code base (https://github.com/lyft/statsite)

**Comment by johnkeates** [comment]
Let's see what others (or @armon) have to say for the next 2-3 days, even with 3 volunteers we would have enough people to get an org going.

**Comment by kuba--** [comment]
Make sense, but which repo will be a base fork?

**Comment by theatrus** [comment]
I imagine this repo would be the base fork as its the one most people are already running. I can take the multi-sink + built-in HTTP fork (+ critical bug fix to sampling) and merge it back in with all the changes in the upstream later (build system, event system, etc).

**Comment by johnkeates** [comment]
Using this repo would indeed be the best plan, most forks are based on this one and merge back in to this one. Changing that will make it harder for everyone to add their pending PR's. 

I'm trying to figure out if I can break down my monster-PR as to make the merging for others easier, the alternative would be me merging first and everyone else merging on top of that.

I've taken the liberty of setting up an org named 'statsite', but it's @armon his call on weather that's okay. It's his name after all, and while I'm not really all that interested in legal aspects, I just don't want an unfriendly break.

**Comment by armon** [comment]
Hey all! Funny I was just thinking in the shower about emailing contributors to give commit access. Unfortunately my days are dominated by management and I've neglected the project. I would be happy to move it to an organization.

**Comment by armon** [comment]
@johnkeates Do you want me to just transfer this to that organization?

**Comment by armon** [comment]
CC: @sleepybishop @melkor217 who have also made contributions.

**Comment by johnkeates** [comment]
I suppose it makes sense to transfer it, great minds think alike eh ;-)
I'll start off with adding us four, and you can transfer whenever you feel like it.

**Comment by armon** [comment]
@johnkeates Transfered! Thanks so much, and many apologies for being slow to do this.

**Comment by johnkeates** [comment]
@armon thanks! and no worries about being busy, we all have jobs taking away our attention and time from stuff like this ;) I think this is a good move, with a bit of luck we'll get a proper community drive behind statsite and your project will go on and grow on it's own!

I'm closing this issue since it's "resolved", thanks for taking the time to make this happen in a neat fashion.
