### ISSUE TITLE
cannot find input file: `Makefile.in'

### ISSUE THREAD

**Issue by gilessbrown** [statsite/statsite#219]
I get this on a new 14.04 Ubuntu VM ...
```shell
$ git clone https://github.com/armon/statsite.git
$ cd statsite
$ ./bootstrap.sh
$ ./configure
....
config.status: error: cannot find input file: `Makefile.in'
```

If I uncomment "autoheader" in bootstrap.sh it seems to work.  Can we get this uncommented?

I ended up here as part of trying to use: https://github.com/obfuscurity/synthesize

Cheers,
Giles

**Comment by relovution** [comment]
Can confirm this issue. Already during running `./bootstrap.sh` one can see the error `configure.ac:26: error: required file 'src/buildconfig.h.in' not found`. Uncommenting autoheader as stated above fixes this.

**Comment by johnkeates** [comment]
Yes, it should be commented out. The issue is that you are using master instead of the 0.8.0 release which does work. The master branch is not 'stable', as in, it does work from a code perspective and runs tests, but if you want a safe and known-working source release, check the releases tab.

**Comment by gilessbrown** [comment]
OK, thanks @johnkeates.

**Comment by johnkeates** [comment]
By the way, I'll ask the other members if we want to release a new version soon, since we have a few nice fixes in place, and in that one, we'll have autoheader working again as it should.
