### ISSUE TITLE
Package building

### ISSUE THREAD

**Issue by ROunofF** [statsite/statsite#220]
I'm interested in building a debian package (I already builded a rpm a couple of months ago)

I see you have the base for all of this. But it seems you're missing the few final command. Would you mind sharing those that would make this process repeatable for people out there?

Apparently I can't label this myself to questions...

**Comment by johnkeates** [comment]
I'm currently working on OTFC with debian mentors on getting the package into Debian itself. Creating a .deb file is working out of the box, you can use the di/du scripts from debian itself. It boils down to something like` make [s]dist; dpkg-buildpackage -us -uc;`

**Comment by pantocrator27** [comment]
Does debian/ubuntu have the concept of clean room package building like what Fedora has called mock https://fedoraproject.org/wiki/Using_Mock_to_test_package_builds

**Comment by johnkeates** [comment]
Yes, it's used with buildd. There are many options and components, including pbuilder which is a cleanroom builder.
