### ISSUE TITLE
RPM won't build cleanly on master

### ISSUE THREAD

**Issue by franmrl** [statsite/statsite#226]
After running the steps in the README.md, on a Centos 6.6, `make rpms` command will fail with a failure to find the build binary in the `src` directory.

```
+ install -m 755 src/statsite /tmp/rpm-build/BUILDROOT/statsite-0.8.0-1.el6.x86_64/usr/sbin
install: cannot stat `src/statsite': No such file or directory
```
I see that the binary is actually on the root directory, instead of inside src. I didn't delve into the Makefile logic, but it seems that either is being placed in the wrong place, or it's being expected in the wrong place, breaking the rpm build.

Just removing the `src/` on spec file on line 52 **apparently** solves the issue, and the binary can be correctly packed.

**Comment by johnkeates** [comment]
I accepted the PR for this, please check if all is well now :-) If so, feel free to close this issue.
