### ISSUE TITLE
statsite will not start if ipv6 is disabled on CentOS 6

### ISSUE THREAD

**Issue by trenb** [statsite/statsite#239]
If you try to start statsite on a CentOS 6 box with ipv6 disabled you get the following errors:
```
Starting statsite: statsite version 0.8.0
statsite[3510]: Starting statsite.
statsite[3510]: stdin is disabled
statsite[3510]: TCP port is disabled
statsite[3510]: Failed to bind on any UDP socket!
statsite[3510]: Failed to initialize networking!
```
If I re-enable ipv6 statsite will start just fine. Unfortunately we disable ipv6 on all our centos 5 and 6 servers.

**Comment by johnkeates** [comment]
This is strange, the error you are having means you didn't enable TCP in statsite (regardless of your OS), but the failure means the default UDP port could not be bound to. How did you configure your statsite?

**Comment by trenb** [comment]
Here ya go!

```
[statsite]
port = 8125
udp_port = 8125
log_level = INFO
log_facility = local0
daemonize = 1
pid_file = /var/run/statsite/statsite.pid
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
gauges_prefix = gauges.
counts_prefix =
timers_prefix = timers.
stream_cmd = python sinks/graphite.py graphite 2003 statsitetest.
```

This same config will not work once ipv6 is disabled.

**Comment by johnkeates** [comment]
Looks like it's not working because the OS won't give you a socket on 8125. Perhaps the port is in use, and enabling IPv6 allows it to listen on IPv6 and leave IPv4 as it was? With IPv6 off and IPv4 in use, it would make sense that it can't listen. Anyway, statsite doesn't do anything different regardless of IPv4/IPv6, it seems your OS might be the one with the issue. (We have mixed dual stack and IPv4-only machines that work fine)

**Comment by trenb** [comment]
Here's netstat before ipv6 is disabled:
```
[0] root@statsite.test:/etc/statsite# netstat -nap | grep statsite
tcp        0      0 :::8125                     :::*                        LISTEN      8255/statsite
udp        0      0 :::8125                     :::*                                    8255/statsite
unix  2      [ ]         DGRAM                    30947  8255/statsite
```
Here's the disable for ipv6
```
cat disable-ipv6.conf
options ipv6 disable=1
```
After rebooting the machine so the ipv6 disable can take effect, statsite no longer can run:
```
[0] root@statsite.test:~# service statsite start
Starting statsite: statsite version 0.8.0
                                                           [  OK  ]
```
and the errors:
```
Apr 26 20:07:21 statsite statsite[2763]: Daemonizing.
Apr 26 20:07:21 statsite statsite[2764]: Starting statsite.
Apr 26 20:07:21 statsite statsite[2764]: stdin is disabled
Apr 26 20:07:21 statsite statsite[2764]: Failed to bind on any TCP socket!
Apr 26 20:07:21 statsite statsite[2764]: Failed to initialize networking!
```
If I re-enable ipv6 support, statsite will start.

**Comment by johnkeates** [comment]
What does netstat show after the failed start?

**Comment by trenb** [comment]
Here ya go:
```
[0] root@statsite.test:~# netstat -nap | grep LISTEN
tcp        0      0 0.0.0.0:8139                0.0.0.0:*                   LISTEN      2358/ruby
tcp        0      0 0.0.0.0:53679               0.0.0.0:*                   LISTEN      1867/rpc.statd
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1833/rpcbind
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      2208/sshd
tcp        0      0 127.0.0.1:199               0.0.0.0:*                   LISTEN      2196/snmpd
```

**Comment by trenb** [comment]
If I remove the disable-ipv6.conf from /etc/modprobe.d to re-enable ipv6 support and reboot, statsite start no problem.
```
[0] root@statsite.test:~# netstat -nap | grep LISTEN
tcp        0      0 0.0.0.0:8139                0.0.0.0:*                   LISTEN      2293/ruby
tcp        0      0 0.0.0.0:111                 0.0.0.0:*                   LISTEN      1835/rpcbind
tcp        0      0 0.0.0.0:22                  0.0.0.0:*                   LISTEN      2204/sshd
tcp        0      0 0.0.0.0:49910               0.0.0.0:*                   LISTEN      1867/rpc.statd
tcp        0      0 127.0.0.1:199               0.0.0.0:*                   LISTEN      2192/snmpd
tcp        0      0 :::111                      :::*                        LISTEN      1835/rpcbind
tcp        0      0 :::46490                    :::*                        LISTEN      1867/rpc.statd
tcp        0      0 :::8125                     :::*                        LISTEN      2248/statsite
```

**Comment by johnkeates** [comment]
Very strange. Looking at the sources I see the socket setup as follows:

````
    hints.ai_family = AF_UNSPEC;    /* Allow IPv4 or IPv6 */
    hints.ai_socktype = SOCK_STREAM; /* Datagram socket */
    hints.ai_flags = AI_PASSIVE;
    hints.ai_protocol = 0;          /* Any protocol */
    hints.ai_canonname = NULL;
    hints.ai_addr = NULL;
    hints.ai_next = NULL;
````

It doesn't seem to specify anything special, and explicitly sets the interface to not care what kind of IP it is.

Could you try udp_port = 8123 and tcp_port=0?

**Comment by trenb** [comment]
Sure. I've re-enabled ipv6, and made the config changes you requested:
```
[statsite]
port = 0
udp_port = 8125
log_level = INFO
log_facility = local0
daemonize = 1
pid_file = /var/run/statsite/statsite.pid
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
gauges_prefix = gauges.
counts_prefix =
timers_prefix = timers.
stream_cmd = python sinks/graphite.py graphite 2003 statsitetest.
```
And here's trying to start statsite:
```
[0] root@statsite.test:~# service statsite start
Starting statsite: statsite version 0.8.0
                                                           [  OK  ]
[0] root@statsite.test:~# tail /var/log/messages
Apr 26 20:16:16 statsite statsite[2412]: Daemonizing.
Apr 26 20:16:16 statsite statsite[2413]: Starting statsite.
Apr 26 20:16:16 statsite statsite[2413]: stdin is disabled
Apr 26 20:16:16 statsite statsite[2413]: TCP port is disabled
Apr 26 20:16:16 statsite statsite[2413]: Failed to bind on any UDP socket!
Apr 26 20:16:16 statsite statsite[2413]: Failed to initialize networking!
```

**Comment by trenb** [comment]
Sorry, I missed your request for me to use udp 8123. Here ya go:
```
[0] root@statsite.test:/etc/statsite# cat statsite.conf
[statsite]
port = 0
udp_port = 8123
log_level = INFO
log_facility = local0
daemonize = 1
pid_file = /var/run/statsite/statsite.pid
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
gauges_prefix = gauges.
counts_prefix =
timers_prefix = timers.
stream_cmd = python sinks/graphite.py graphite.mci.airg.lan 2003 statsitetest.
```
and trying to start:
```
[0] root@statsite.test:/etc/statsite# service statsite start
Starting statsite: statsite version 0.8.0
                                                           [  OK  ]
[0] root@statsite.test:/etc/statsite# tail /var/log/messages
Apr 26 20:18:35 statsite statsite[2475]: Daemonizing.
Apr 26 20:18:35 statsite statsite[2476]: Starting statsite.
Apr 26 20:18:35 statsite statsite[2476]: stdin is disabled
Apr 26 20:18:35 statsite statsite[2476]: TCP port is disabled
Apr 26 20:18:35 statsite statsite[2476]: Failed to bind on any UDP socket!
Apr 26 20:18:35 statsite statsite[2476]: Failed to initialize networking!
```

**Comment by johnkeates** [comment]
Very strange. The code for UDP and TCP is practically the same.

If you check https://github.com/statsite/statsite/blob/ca2f7384205a923adeb2006269904692d3387b3a/src/networking.c#L117 you'll see that first it sets the default parameters for the socket and then your chosen port numbers. It then checks to make sure that the config is valid and starts looping over your interfaces one by one until it can connect, and when it all fails it gives that 'failed to bind on any' issue.

It might be possible that it's not able to bind on any of the interfaces for the listening socket due to some specific configuration in your machine, especially since statsite doesn't even "know" about IPv6/IPv4, it just eats a socket, and it does work on other Linux machines (between 3.x and 4.x on Debian-alikes and RHEL types at least from my tests). The original author also had it working, and I'm not an expert on the code, but it doesn't seem like it even could influence the socket based on your stack settings :( I'm sorry, but this doesn't look like something I would be able to help you with. I could setup a fresh vagrant box and share the setup...

**Comment by trenb** [comment]
Can you on a centos 6 box add:
```
options ipv6 disable=1
```
to /etc/modprobe.d/disable-ipv6.conf

and reboot and then try yourself?

**Comment by trenb** [comment]
So long as ipv6 is not disabled in the kernel, statsite is happy. As soon as I disable ipv6 support in the kernel, it doesn't work.

I understand this is an edge case, and I can work around this, but I thought it would be good to log this issue in case anyone else runs into this problem.

**Comment by johnkeates** [comment]
I agree, if it is an issue it should be resolved, especially since (as far as my opinion goes) this is basic functionality. I'll setup a fresh box.

**Comment by trenb** [comment]
Thanks @johnkeates for your assistance on this.

**Comment by johnkeates** [comment]
I have replicated the issue in a clean environment, so it's definitely something about the sockets/network API that should be called different, or maybe it's an OS thing. I'm going to test on CentOS 7 now and Debian again, to be sure.

**Comment by trenb** [comment]
This works fine on CentOS7 in my testing (or a centos 6 container on a centos 7 host for that matter). I do not think you can disable ipv6 in the same way for CentOS7 that you could for CentOS6.

Anyhow, glad you are able to reproduce. If you need anything else from my end, please let me know.

**Comment by johnkeates** [comment]
Yep, works fine on CentOS 7. Removing the module (rmmod), disabling IPv6 via sysctl none of it breaks the socket. Seems to be something specific to CentOS 6 and/or it's kernel.

**Comment by trenb** [comment]
Can you try disabling ipv6 at the kernel level by adding "ipv6.disable=1" to your kernel command line?

**Comment by johnkeates** [comment]
Yes, that breaks it again. Seems the AddressFamily / AF_UNSPEC definitely breaks with IPv6 killed that way. There is a page on IPv6 disabling for CentOS 7 listing potential issues with programs that normally select the address family automatically: https://wiki.centos.org/FAQ/CentOS7#head-8984faf811faccca74c7bcdd74de7467f2fcd8ee so it seems this issue isn't very statsite-specific, but can be 'solved' or worked around by specifying an address and/or address family.

**Comment by trenb** [comment]
Yeah, you're correct, this has nothing to do with statsite. I think this can be closed. 

Thanks for your time @johnkeates

**Comment by johnkeates** [comment]
Well, before I close this, I should probably document it. But at the same time, it seems some applications manage to scan or identify what address families they should use. Of course, this should really be the job of the OS to handle, and the API/libraries should "just work". (but the world is far form perfect...)

I'll see if I can get some example C code to detect this. If I can make it work I'll patch it in. Otherwise, I myself won't be able to help you, but maybe someone else knows what code is required to fix it.

**Comment by johnkeates** [comment]
Additional info: MariaDB seems to have run into this issue too: https://jira.mariadb.org/browse/MDEV-8083 and MySQL has had a patch for this: https://github.com/mysql/mysql-server/commit/da66e3850d0b186a3c86e06daa4bc3208ad5cc62

**Comment by johnkeates** [comment]
I've built a somewhat working IPv6 detector!

**Comment by johnkeates** [comment]
And after building the stuff, I figured you should simply set the bind_address... haha.

So, @trenb add `bind_address = 0.0.0.0` to your config and it will run on IPv6-disabled kernels fine.

**Comment by trenb** [comment]
Just wanted to confirm, setting the bind_address has resolved my issues. Thank you again for your help @johnkeates
