### ISSUE TITLE
sink working but whisper files are full of zeros

### ISSUE THREAD

**Issue by cmorgan** [statsite/statsite#240]
I've tested the stream_cmd with cat > /tmp/test
all looking good

when using the python sink whisper files are created and filled with zeros, but never have any values.
Am I missing something?
Thanks

**Comment by albertored** [comment]
This will be fixed in #241

**Comment by johnkeates** [comment]
Merged

**Comment by johnkeates** [comment]
@cmorgan let me know if this fixed it for you as well, would be good to know!

**Comment by cmorgan** [comment]
nice one, seems to be working now. filling up nicely. thanks
