### ISSUE TITLE
unable to start statsite using  ./statsite -f statsite.conf

### ISSUE THREAD

**Issue by osho278** [statsite/statsite#264]
I am unable to install statsite using  **./statsite -f statsite.conf** , i have been working on it for about a day without any luck. it only shows statsite version.

i have tried placing the config file in /etc/statsite.conf and /etc/statsite/statsite.conf without any luck.
although when i run ./statsite ,then it works fine.  I need to change we configs but unable to do it.

Is it a known issue ??
![image](https://user-images.githubusercontent.com/4320723/27918781-963b3f2a-628d-11e7-9fb6-db9945756fe0.png)

**Comment by johnkeates** [comment]
Check with top or ps, statsite is probably already running. If you have daemonize=1 in your config, it starts and disconnects from your terminal. This is normal.

**Comment by osho278** [comment]
PS output

[root@localhost statsite]# cat /etc/redhat-release
CentOS Linux release 7.3.1611 (Core)
[root@localhost statsite]# ./statsite -f statsite.conf
statsite version 0.8.1
[root@localhost statsite]# ps -ef | grep statsite
root     21666 32078  0 21:03 pts/2    00:00:00 grep --color=auto statsite


**Its not running**

**Comment by osho278** [comment]
with deamonize=1 , i checked /var/log/messages ,
![image](https://user-images.githubusercontent.com/4320723/27919428-48085c0a-628f-11e7-8619-6941bb170423.png)

 running this using sudo also had no luck .... maybe my directory permissions are not correct .
anyways  i will check and keep updating

**Comment by johnkeates** [comment]
Do those directories exist? Normally, you would use the packaged version of statsite and that will make sure everything is in place.

**Comment by osho278** [comment]
i think that was the problem , directories was not present . I should have checked that before raising a issue here. I think it is solved . No problem at all . Although i have a small doubt . Statsite was written in 'c' so as to overcome the performance issues of statsd . now have a sink (backend) written in node or python wont have any performance impact ? i see all the sinks either in python or node ? any explanation about that

**Comment by johnkeates** [comment]
Sinks can be written in any language. They are not used to aggregate but to distribute the data. The performance issue was with aggregation, not with sinking the data to the next host I believe.

The idea with statsd and statsite is that you have a update interval where statsite remembers the data for a bit and then pushes it out in bundles so you don't have a constant stream of data with overhead.

You can write sinks in any language, as long as it can be started like a shell command and accepts the data via a stdio input stream. The ones we have right now are mostly contributed I think.
