### ISSUE TITLE
Config CSV parsing doesn't work with spaces

### ISSUE THREAD

**Issue by mheffner** [statsite/statsite#265]
The following:
```
timers_include = count, mean, stdev, sum, sum_sq, lower, upper
```
ends up just parsing as `count`.

Without spaces:
```
timers_include = count,mean,stdev,sum,sum_sq,lower,upper
```
seems to work fine.

There doesn't appear to be any error logged on the first version, so you can't tell why many timer fields aren't rendering.

**Comment by sleepybishop** [comment]
the parser in csv_to_included_metrics_config() in config.c is pretty basic. 
it should be trivial to add a few lines to eat whitespace.

standby for a PR

**Comment by johnkeates** [comment]
Since this is fixed, I'll close this issue.
