### ISSUE TITLE
when i try compile, arise this error

### ISSUE THREAD

**Issue by vaclandic** [statsite/statsite#269]
checking for strncasecmp... yes                                                                                                                               
checking for strtol... yes                                                                                                                                    
configure: line 5955: syntax error near unexpected token `CHECK,'                                                                                             
configure: line 5955: `PKG_CHECK_MODULES(CHECK, check >= 0.9.7, have_check="yes", { $as_echo "$as_me:${as_lineno-$LINENO}: WARNING: Check not found; cannot ru
n unit tests!" >&5'

**Comment by vaclandic** [comment]
i m stupid) sorry)

**Comment by dcallao** [comment]
@vaclandic how did you resolve this error? I get the same error.

**Comment by johnkeates** [comment]
@dcallao
He probably installed `check` which was missing and thus generated the warning about check missing which then halted configure.

If you follow the instructions form the README file you'll be able to install it: https://github.com/statsite/statsite#install and that should solve it for you as well.
