### ISSUE TITLE
Flushing explanation

### ISSUE THREAD

**Issue by lzap** [statsite/statsite#279]
Hello,

I struggle to understand the basic concept from the README. At some point, statsite starts flushing the results to a sink process, but I can't find any mention on if it keeps the sink process opened, or if it closes and re-spawn them on each flush.

I tried reading the source and I *believe* it closes the sink program on every flush. Can you confirm please? Thanks!

**Comment by lzap** [comment]
It closes it!

**Comment by johnkeates** [comment]
I'm still on vacation and it doesn't seem like anyone else has picked up on this. Did you get your question resolved?
