### ISSUE TITLE
Gauges are broken and are incompatible with statsd

### ISSUE THREAD

**Issue by dannyfallon** [statsite/statsite#69]
Gauges in statsite are broken - they are not sent every flush interval and they do not support deltas like it mentions in the documentation (+/- values).

I sent a test gauge (`test_gauge:123|g`) to both statsD and statsite, the following are the results 
## StatsD

```
[danny@dannyfallon ~/src/statsd (master)]$ cat config.js 
{
  graphitePort: 2004
, graphiteHost: "127.0.0.1"
, port: 8125
, flushInterval: 10000
, dumpMessages: true
, debug: true
, backends: [ "./backends/graphite" ]
}

[danny@dannyfallon ~/src/statsd (master)]$ node stats.js config.js 
19 Jun 15:05:29 - reading config file: config.js
19 Jun 15:05:29 - server is up
19 Jun 15:05:29 - DEBUG: Loading backend: ./backends/graphite
19 Jun 15:05:39 - DEBUG: numStats: 2
19 Jun 15:05:48 - DEBUG: test_gauge:123|g
19 Jun 15:05:49 - DEBUG: numStats: 4
19 Jun 15:05:59 - DEBUG: numStats: 4
...
```

At the same time I was using tcpdump to see what was going to Graphite and I see the gauge is sent every flush interval:

```
[danny@dannyfallon ~/src/statsd (master)]$ sudo tcpdump -l -t -A -s0 dst port 2004 | grep gauges
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 65535 bytes
stats.gauges.test_gauge 123 1403186760
stats.gauges.test_gauge 123 1403186770
stats.gauges.test_gauge 123 1403186780
stats.gauges.test_gauge 123 1403186790
stats.gauges.test_gauge 123 1403186800
stats.gauges.test_gauge 123 1403186810
...
```
## Statsite

```
[danny@dannyfallon ~/src/statsite (master)]$ cat statsite.conf
[statsite]
port = 8125
udp_port = 8125
flush_interval = 10
timer_eps = 0.01
set_eps = 0.02
stream_cmd = python sinks/graphite.py 127.0.0.1 2004

[danny@dannyfallon ~/src/statsite (master)]$ ./statsite -f statsite.conf
Jun 19 15:18:28 dannyfallon.local statsite[51551] <Info>: Starting statsite.
Jun 19 15:18:28 dannyfallon.local statsite[51551] <Info>: stdin is disabled
Jun 19 15:18:28 dannyfallon.local statsite[51551] <Info>: Listening on tcp ':::8125'
Jun 19 15:18:28 dannyfallon.local statsite[51551] <Info>: Listening on udp ':::8125'.
Jun 19 15:19:55 dannyfallon.local statsite[51551] <Debug>: Accepted client connection: 0.0.0.0 50940 [8]
Jun 19 15:19:55 dannyfallon.local statsite[51551] <Debug>: Closed client connection. [8]
Jun 19 15:19:55 dannyfallon.local statsite[51551] <Debug>: Closed connection. [8]
```

And the TCP dump

```
[danny@dannyfallon ~/src/statsite (master)]$ sudo tcpdump -l -t -A -s0 dst port 2004 | grep gauges
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 65535 bytes
>....z'.statsite.gauges.test_gauge 123.000000 1403187598
^C171 packets captured
10852 packets received by filter
0 packets dropped by kernel

[danny@dannyfallon ~/src/statsd (master)]$ date +%s
1403187875
```

As you can see, I left the tcpdump running for almost 300 seconds (or around 30 flush intervals) and the gauge was sent just once, when I initially set it.

This is the same bug mentioned in [this issue](https://github.com/armon/statsite/issues/25).

On further investigation I tried to decrement the gauge by sending `test_gauge:-123|g` as in your documentation. I expected the value to be 0, since the gauge was initialised as 123.  What I got was -123. This is the result from TCP dump

```
tcpdump: data link type PKTAP
tcpdump: verbose output suppressed, use -v or -vv for full protocol decode
listening on pktap, link-type PKTAP (Packet Tap), capture size 65535 bytes
>..8.}+.statsite.gauges.test_gauge -123.000000 1403188388
```

If you want statsd compatiblity then gauges should be kept in memory and all gauges are sent with _every_ flush. Keeping the gauge in memory also allows delta operations to be performed.

StatsD offers an optional config variable that allows you to not send gauges in every flush but this still keeps them in memory so you can do delta operations from time to time.

**Comment by DevJackSmith** [comment]
Wasted hours on downloading, installing, configuring and troubleshooting, just to finally google that statsite gauges don't work and get this. I'm not asking for the change, I understand you don't want this option. But can you maybe please add one line in Readme to warn people that statsite doesn't keep gauges after each flush? (but can be done with custom code). Would also love to see that code for graphite sink, so i can manually add it.
