### ISSUE TITLE
multiple stream_cmds

### ISSUE THREAD

**Issue by tj** [statsite/statsite#80]
would be awesome

**Comment by dpkp** [comment]
Trying to get something like `stream_cmd = tee >(python sinks/foobar.py) | python sinks/graphite.py 127.0.0.1 2003 ''` working, but it seems like statsite doesn't support subshell syntax here. Are subshells possible w/ different syntax? Or is the only option here to write a wrapper sink?

Our goal is to manage sink configuration externally (via chef) w/o requiring code changes to add, remove, or reconfigure sinks. That said, we could always write the sink dynamically via chef, but that isn't ideal.

**Comment by theatrus** [comment]
You may be interested in the twitter-forks/statsite version which features multiple sink support. 

I haven't upstreamed any changes yet pending doc cleanups.

**Comment by armon** [comment]
@dpkp That is also a feature of shells, while statsite just does a fork/exec. You could try to prefix that whole command with "/bin/bash -c" and run it under a shell.

**Comment by dpkp** [comment]
@theatrus: wasn't aware of twitter-forks/statsite, will take a look.
@armon: of course! thanks for the hint.
